AddCSLuaFile()
return {
	AvoidWalls = true,
	BecomeSquid = true,
	CanHealInk = true,
	CanHealStand = true,
	CanReloadInk = true,
	CanReloadStand = true,
	DoomStyle = false,
	DrawCrosshair = true,
	DrawInkOverlay = true,
	Enabled = {true, order = 1, serverside = true},
	FF = {false, order = 2, serverside = true},
	Gain = {
		InkAmount = {100, min = 1, max = 500, decimals = 0, order = 2, serverside = true},
		MaxHealth = {100, min = 1, max = 500, decimals = 0, order = 1, serverside = true},
	},
	InkColor = {1, hidden = true},
	LeftHand = false,
	MoveViewmodel = true,
	NewStyleCrosshair = false,
	NoRefract = {false, order = 1, clientside = true},
	Playermodel = {1, hidden = true},
	RTResolution = {1, hidden = true},
	ToggleADS = false,
	weapon_splatoonsweps_blaster_base = {
		HurtOwner = {false, order = 1, serverside = true},
	},
	weapon_splatoonsweps_charger = {
		UseRTScope = false,
		weapon_splatoonsweps_herocharger = {Level = {0, min = 0, max = 3}, __subcategory = true},
	},
	weapon_splatoonsweps_shooter = {
		weapon_splatoonsweps_heroshot = {Level = {0, min = 0, max = 3}, __subcategory = true},
		weapon_splatoonsweps_octoshot = {Advanced = true, __subcategory = true},
		weapon_splatoonsweps_nzap85 = {PistolStyle = false, __subcategory = true},
		weapon_splatoonsweps_nzap89 = {PistolStyle = false, __subcategory = true},
		weapon_splatoonsweps_nzap83 = {PistolStyle = false, __subcategory = true},
	},
}
