AddCSLuaFile()
return {
	AvoidWalls = true,
	BecomeSquid = true,
	CanHealInk = true,
	CanHealStand = true,
	CanReloadInk = true,
	CanReloadStand = true,
	DoomStyle = false,
	DrawCrosshair = true,
	DrawInkOverlay = true,
	Enabled = {true, order = 1, serverside = true},
	FF = {false, order = 2, serverside = true},
	InkColor = {1, hidden = true},
	LeftHand = false,
	MoveViewmodel = true,
	NewStyleCrosshair = false,
	Playermodel = {1, hidden = true},
	RTResolution = {1, hidden = true},
	ToggleADS = false,
	weapon_charger = {
		UseRTScope = false,
		weapon_herocharger = {Level = {0, min = 0, max = 3}, __subcategory = true},
	},
	weapon_shooter = {
		weapon_heroshot = {Level = {0, min = 0, max = 3}, __subcategory = true},
		weapon_octoshot = {Advanced = true, __subcategory = true},
		weapon_nzap85 = {PistolStyle = false, __subcategory = true},
		weapon_nzap89 = {PistolStyle = false, __subcategory = true},
		weapon_nzap83 = {PistolStyle = false, __subcategory = true},
	},
}
