
local ss = SplatoonSWEPs
if not ss then return end
local lang = GetConVar "gmod_language" :GetString()
local WeaponNames = {
	".52 Gal",
	".52 Gal Deco",
	".96 Gal",
	".96 Gal Deco",
	"Aerospray MG",
	"Aerospray PG",
	"Aerospray RG",
	"Bamboozler 14 Mk Ⅰ",
	"Bamboozler 14 Mk Ⅱ",
	"Bamboozler 14 Mk Ⅲ",
	"Blaster",
	"Custom Blaster",
	"Carbon Roller",
	"Carbon Roller Deco",
	"Dual Squelcher",
	"Custom Dual Squelcher",
	"Dynamo Roller",
	"Gold Dynamo Roller",
	"Tempered Dynamo Roller",
	"E-liter 3K",
	"Custom E-liter 3K",
	"E-liter 3K Scope",
	"Custom E-liter 3K Scope",
	"H-3 Nozzlenose",
	"H-3 Nozzlenose D",
	"Cherry H-3 Nozzlenose",
	"Heavy Splatling",
	"Heavy Splatling Deco",
	"Heavy Splatling Remix",
	"Hero Charger Replica",
	"Hero Roller Replica",
	"Hero Shot Replica",
	"Hydra Splatling",
	"Custom Hydra Splatling",
	"Inkbrush",
	"Inkbrush Nouveau",
	"Permanent Inkbrush",
	"Jet Squelcher",
	"Custom Jet Squelcher",
	"L-3 Nozzlenose",
	"L-3 Nozzlenose D",
	"Luna Blaster",
	"Luna Blaster Neo",
	"Mini Splatling",
	"Refurbished Mini Splatling",
	"Zink Mini Splatling",
	"N-ZAP '83",
	"N-ZAP '85",
	"N-ZAP '89",
	"Octobrush",
	"Octobrush Nouveau",
	"Octoshot Replica",
	"Range Blaster",
	"Custom Range Blaster",
	"Grim Range Blaster",
	"Rapid Blaster",
	"Rapid Blaster Deco",
	"Rapid Blaster Pro",
	"Rapid Blaster Pro Deco",
	"Slosher",
	"Slosher Deco",
	"Soda Slosher",
	"Sloshing Machine",
	"Sloshing Machine Neo",
	"Splash-o-matic",
	"Splash-o-matic Neo",
	"Splat Charger",
	"Kelp Splat Charger",
	"Bento Splat Charger",
	"Splat Roller",
	"Krak-On Splat Roller",
	"CoroCoro Splat Roller",
	"Splatterscope",
	"Kelp Splatterscope",
	"Bento Splatterscope",
	"Splattershot",
	"Tentatek Splattershot",
	"Wasabi Splattershot",
	"Splattershot Jr.",
	"Custom Splattershot Jr.",
	"Splattershot Pro",
	"Forge Splattershot Pro",
	"Berry Splattershot Pro",
	"Sploosh-o-matic",
	"Sploosh-o-matic Neo",
	"Sploosh-o-matic 7",
	"Classic Squiffer",
	"Fresh Squiffer",
	"New Squiffer",
	"Tri-Slosher",
	"Tri-Slosher Nouveau",
}

WeaponNames.ja = {
	".52ガロン",
	".52ガロンデコ",
	".96ガロン",
	".96ガロンデコ",
	"プロモデラーMG",
	"プロモデラーPG",
	"プロモデラーRG",
	"14式竹筒銃・甲",
	"14式竹筒銃・乙",
	"14式竹筒銃・丙",
	"ホットブラスター",
	"ホットブラスターカスタム",
	"カーボンローラー",
	"カーボンローラーデコ",
	"デュアルスイーパー",
	"デュアルスイーパーカスタム",
	"ダイナモローラー",
	"ダイナモローラーテスラ",
	"ダイナモローラーバーンド",
	"リッター3K",
	"リッター3Kカスタム",
	"3Kスコープ",
	"3Kスコープカスタム",
	"H3リールガン",
	"H3リールガンD",
	"H3リールガンチェリー",
	"バレルスピナー",
	"バレルスピナーデコ",
	"バレルスピナーリミックス",
	"ヒーローチャージャー レプリカ",
	"ヒーローローラー レプリカ",
	"ヒーローシューター レプリカ",
	"ハイドラント",
	"ハイドラントカスタム",
	"パブロ",
	"パブロ・ヒュー",
	"パーマネント・パブロ",
	"ジェットスイーパー",
	"ジェットスイーパーカスタム",
	"L3リールガン",
	"L3リールガンD",
	"ノヴァブラスター",
	"ノヴァブラスターネオ",
	"スプラスピナー",
	"スプラスピナーリペア",
	"スプラスピナーコラボ",
	"N-ZAP83",
	"N-ZAP85",
	"N-ZAP89",
	"ホクサイ",
	"ホクサイ・ヒュー",
	"オクタシューター レプリカ",
	"ロングブラスター",
	"ロングブラスターカスタム",
	"ロングブラスターネクロ",
	"ラピッドブラスター",
	"ラピッドブラスターデコ",
	"Rブラスターエリート",
	"Rブラスターエリートデコ",
	"バケットスロッシャー",
	"バケットスロッシャーデコ",
	"バケットスロッシャーソーダ",
	"スクリュースロッシャー",
	"スクリュースロッシャーネオ",
	"シャープシューター",
	"シャープシューターネオ",
	"スプラチャージャー",
	"スプラチャージャーワカメ",
	"スプラチャージャーベントー",
	"スプラローラー",
	"スプラローラーコラボ",
	"スプラローラーコロコロ",
	"スプラスコープ",
	"スプラスコープワカメ",
	"スプラスコープベントー",
	"スプラシューター",
	"スプラシューターコラボ",
	"スプラシューターワサビ",
	"わかばシューター",
	"もみじシューター",
	"プライムシューター",
	"プライムシューターコラボ",
	"プライムシューターベリー",
	"ボールドマーカー",
	"ボールドマーカーネオ",
	"ボールドマーカー7",
	"スクイックリンα",
	"スクイックリンγ",
	"スクイックリンβ",
	"ヒッセン",
	"ヒッセン・ヒュー",
}

local WeaponNames2 = {
	"Clash Blaster",
	"Dapple Dualies",
	"Dapple Dualies Nouveau",
	"Dark Tetra Dualies",
	"Dualie Squelchers",
	"E-liter 4K",
	"Custom E-liter 4K",
	"E-liter 4K Scope",
	"Custom E-liter 4K Scope",
	"Flingza Roller",
	"Foil Flingza Roller",
	"Glooga Dualies",
	"Goo Tuber",
	"Custom Goo Tuber",
	"Hero Blaster Replica",
	"Hero Brella Replica",
	"Herobrush Replica",
	"Hero Dualie Replicas",
	"Hero Slosher Replica",
	"Hero Splatling Replica",
	"Splat Brella",
	"Firefin Splat Charger",
	"Splat Dualies",
	"Emperry Splat Dualies",
	"Firefin Splatterscope",
	"Squeezer",
	"Tenta Brella",
	"Undercover Brella",
}

WeaponNames2.ja = {
	"クラッシュブラスター",
	"スパッタリー",
	"スパッタリー・ヒュー",
	"クアッドホッパーブラック",
	"デュアルスイーパー",
	"リッター4K",
	"リッター4Kカスタム",
	"4Kスコープ",
	"4Kスコープカスタム",
	"ヴァリアブルローラー",
	"ヴァリアブルローラーフォイル",
	"ケルビン525",
	"ソイチューバー",
	"ソイチューバーカスタム",
	"ヒーローブラスター レプリカ",
	"ヒーローシェルター レプリカ",
	"ヒーローブラシ レプリカ",
	"ヒーローマニューバー レプリカ",
	"ヒーロースロッシャー レプリカ",
	"ヒーロースピナー レプリカ",
	"パラシェルター",
	"スプラチャージャーコラボ",
	"スプラマニューバー",
	"スプラマニューバーコラボ",
	"スプラスコープコラボ",
	"ボトルガイザー",
	"キャンピングシェルター",
	"スパイガジェット",
}

if lang == "ja" then
	ss.Purpose = "ブキを手に取り、イカになれ！"
	ss.Instructions = [[
メイン攻撃: インクを撃つ
サブ攻撃: サブウェポンを使う
リロード: スペシャル発動
スプリント: スーパージャンプ
しゃがみ: イカになる]]
end

ss.PrintName = {}
for i, c in ipairs(ss.WeaponClassNames) do
	ss.PrintName[c] = (WeaponNames[lang] or WeaponNames)[i]
end

if SERVER then return end
steamworks.RequestPlayerInfo("76561198013738310", function(name) ss.AuthorName = name end)
