
AddCSLuaFile()
local ss = SplatoonSWEPs
if not (ss and SWEP) then return end
SWEP.PreSwingSound = "SplatoonSWEPs.RollerPreSwing"
SWEP.SwingSound = "SplatoonSWEPs.RollerSwing"
SWEP.SplashSound = "SplatoonSWEPs.RollerSplashMedium"
SWEP.RollSoundName = ss.DynamoRollerRoll
SWEP.Special = "echolocator"
SWEP.Sub = "sprinker"
SWEP.Variations = {
	{
		Customized = true,
		Skin = 1,
		Special = "inkstrike",
		Sub = "splatbomb",
		Suffix = "gold",
	},
	{
		SheldonsPicks = true,
		Skin = 2,
		Special = "killerwail",
		Sub = "seeker",
		Suffix = "tempered",
	},
}

ss.SetPrimary(SWEP, {
	mSwingLiftFrame = 45,
	mSplashNum = 16,
	mSplashInitSpeedBase = 10,
	mSplashInitSpeedRandomZ = 5,
	mSplashInitSpeedRandomX = 0.5714,
	mSplashInitVecYRate = 0,
	mSplashDeg = 2.5,
	mSplashSubNum = 0,
	mSplashSubInitSpeedBase = 17.5,
	mSplashSubInitSpeedRandomZ = 3.5,
	mSplashSubInitSpeedRandomX = 0,
	mSplashSubInitVecYRate = 0,
	mSplashSubDeg = 7,
	mSplashPositionWidth = 8,
	mSplashInsideDamageRate = 0.38,
	mCorePaintWidthHalf = 30,
	mCorePaintSlowMoveWidthHalf = 13,
	mSlowMoveSpeed = 0,
	mCoreColWidthHalf = 10,
	mInkConsumeCore = 0.001,
	mInkConsumeSplash = 0.2,
	mInkRecoverCoreStop = 20,
	mInkRecoverSplashStop = 50,
	mMoveSpeed = 0.96,
	mCoreColRadius = 4,
	mCoreDamage = 1.6,
	mTargetEffectScale = 2,
	mTargetEffectVelRate = 1.4,
	mSplashStraightFrame = 6,
	mSplashDamageMaxDist = 70,
	mSplashDamageMinDist = 170,
	mSplashDamageMaxValue = 1.25,
	mSplashDamageMinValue = 0.25,
	mSplashOutsideDamageMaxDist = 155,
	mSplashOutsideDamageMinDist = 170,
	mSplashOutsideDamageMaxValue = 0.5,
	mSplashOutsideDamageMinValue = 0.25,
	mSplashDamageRateBias = 1,
	mSplashDrawRadius = 6,
	mSplashPaintNearD = 10,
	mSplashPaintNearR = 22,
	mSplashPaintFarD = 200,
	mSplashPaintFarR = 22,
	mSplashCollisionRadiusForField = 8,
	mSplashCollisionRadiusForPlayer = 12,
	mSplashCoverApertureFreeFrame = -1,
	mSplashSubStraightFrame = 4,
	mSplashSubDamageMaxDist = 10,
	mSplashSubDamageMinDist = 80,
	mSplashSubDamageMaxValue = 1.4,
	mSplashSubDamageMinValue = 0.3,
	mSplashSubDamageRateBias = 1,
	mSplashSubDrawRadius = 3,
	mSplashSubPaintNearD = 10,
	mSplashSubPaintNearR = 18,
	mSplashSubPaintFarD = 200,
	mSplashSubPaintFarR = 15,
	mSplashSubCollisionRadiusForField = 9,
	mSplashSubCollisionRadiusForPlayer = 9,
	mSplashSubCoverApertureFreeFrame = -1,
	mSplashPaintType = 1,
	mArmorTypeObjectDamageRate = 0.4,
	mArmorTypeGachihokoDamageRate = 0.288,
	mPaintBrushType = false,
	mPaintBrushRotYDegree = 0,
	mPaintBrushSwingRepeatFrame = 6,
	mPaintBrushNearestBulletLoopNum = 6,
	mPaintBrushNearestBulletOrderNum = 2,
	mPaintBrushNearestBulletRadius = 10,
	mDropSplashDrawRadius = 0.5,
	mDropSplashPaintRadius = 0,
})
