DecentVehicleDestination.Texts = {
	CVars = {
		DetectionRange = "Decent Vehicle = A vehicle within this distance will drive automatically.",
		DetectionRangeELS = "Decent Vehicle = Detection range of finding cars with ELS to give way.",
		DriveSide = "Decent Vehicle = Determines which side of road Decent Vehicles think.\n0 = Right (Europe, America, etc.)\n1 = Left (UK, Australia, etc.)",
		LockVehicle = "Decent Vehicle = Whether or not Decent Vehicle prevents players from getting in.",
		ShouldGoToRefuel = "Decent Vehicle = 1 = Go to a fuel station to refuel.  0 = Refuel automatically.",
		TimeToStopEmergency = "Decent Vehicle = Time to turn off hazard lights in seconds.",
		TurnonLights = [[Decent Vehicle = The level of using lights.
0 = Disabled
1 = Only use running lights
2 = Use running lights and headlights
3 = Use all lights]],
	},
	Errors = {
		AttachmentNotFound = "Decent Vehicle = attachment vehicle_feet_passenger0 is not found!",
		WaypointNotFound = "Decent Vehicle = Waypoint is not found!",
	},
	OldVersionNotify = "Decent Vehicle = This is an old version.  Check for updates!",
	OnLoad = "You are about to LOAD the waypoints.",
	OnSave = "You are about to SAVE the waypoints.",
	SavedWaypoints = "Decent Vehicle = Waypoints are saved!",
	SaveLoad_Cancel = "Cancel",
	SaveLoad_OK = "OK",
	Tools = {
		Bidirectional = "Bi-directional link",
		BidirectionalHelp = "Connect bi-directional link automatically.",
		Category = "GreatZenkakuMan's tools",
		Description = "Create your own routes for vehicles!",
		DescriptionInMenu = "Create routes for Decent Vehicles.",
		DetectionRange = "Detection range for spawning",
		DetectionRangeELS = "Detection range for finding cars with ELS",
		DrawWaypoints = "Draw waypoints",
		DriveSide = "Is left side of the road",
		FuelStation = "Fuel station",
		FuelStationHelp = "Decent Vehicles will go here to refuel its car.",
		Instructions = "Select a waypoint or a traffic light to link.  Select a vehicle driven by a Decent Vehicle to assign its waypoint group.",
		Left = {
			"Create a new waypoint.",
			"Select another waypoint you want to link to.  Select the same waypoint to remove it.",
		},
		LightLevel = {
			All = "Full lights",
			Headlights = "Running lights and headlights",
			None = "No light",
			Running = "Only running lights",
			Title = "Light level",
		},
		LockVehicle = "Lock vehicle",
		LockVehicleHelp = "If checked, Decent Vehicle prevents other players from getting in.",
		MaxSpeed = "Max speed [km/h]",
		Name = "Decent Vehicle Waypoint Tool",
		PrintName = "Decent Vehicle Waypoint Tool",
		Restore = "Restore waypoints",
		Right = {"Update waypoint."},
		Save = "Save waypoints",
		ServerSettings = "Server settings",
		ShouldGoToRefuel = "Should go finding a fuel station",
		ShowInfo = {
			FuelStation = "Is fuel station = ",
			Group = "Group = ",
			ID = "ID = ",
			SpeedLimit = "Speed limit [km/h] = ",
			UseTurnLights = "Use turn lights = ",
			WaitUntilNext = "Wait until next [seconds] = ",
		},
		ShowUpdates = "Notify the latest updates",
		ShowUpdatesHelp = "If checked, some notifications are shown when this addon is updated.",
		UseTurnLights = "Use turn signals",
		UseTurnLightsHelp = "Decent Vehicles will use turn signals when they go to the waypoint.",
		WaitTime = "Wait time [seconds]",
		WaitTimeHelp = "After Decent Vehicles reached the waypoint, they wait for this seconds.",
		WaypointGroup = "Waypoint group",
		WaypointGroupHelp = "You can force Decent Vehicles to run along specified group of waypoints.\n0 means all vehicles can go there.",
	},
	UndoText = "Undone Decent Vehicle's waypoint",
}

DecentVehicleDestination.Texts.npc_decentvehicle = "Decent Vehicle"
